server:
  port: 8081
  # servlet:
  #   context-path: /Shopme
spring:
  datasource:
    password: 12345678
    url: jdbc:mysql://connecte.cqmi2rkawqln.ap-south-1.rds.amazonaws.com/connecte
    username: rootuser
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 182557182495-4ojqb7gpdf0cee6i97md5b3tns5sbc1e.apps.googleusercontent.com
            client-secret: zpJMafs7JAf4fNVLZirNcRnO
            scope:
            - email
            - profile
          facebook:
            client-id: 385247526176612
            client-secret: 690eed41082352ee7b0e1de7b72975d9
            scope:
            - email
            - public_profile