server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: Arjun@333
    url: jdbc:mysql://localhost:3306/connecte
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 983125206755-jne5pe5f78u88lqpsh228giqe2g6g9af.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 1065065327239672
            client-secret: 36b56b7e6d6540eb7a40d538f8d99c05
            scope:
            - email
            - public_profile